name: Build

on:
  #手动编译
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_cortex-a53
          - aarch64_cortex-a72
          - aarch64_generic
          - arm_cortex-a7_neon-vfpv4
          - arm_cortex-a8_vfpv3
          - mips64_octeonplus
          - mips_24kc
          - mips_mips32
          - mipsel_24kc
          - mipsel_24kc_24kf
          - mipsel_mips32
          - x86_64

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get v2ray-geodata
        run: |
          git clone https://github.com/sbwml/v2ray-geodata

      - name: Building packages
        uses: sbwml/openwrt-gh-action-sdk@go1.23
        env:
          ARCH: ${{ matrix.arch }}-openwrt-22.03
          FEEDNAME: packages_ci
          PACKAGES: luci-app-mosdns
          NO_REFRESH_CHECK: true

      - name: Upload artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          tag: ${{ github.ref_name }}
          name: ${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk

      - name: Upload packages
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "bin/packages/${{ matrix.arch }}/packages_ci/*.ipk"
